[package]
name = "cc2"
version = "0.1.0"
edition = "2024"
authors = ["Huseen Munye"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/hmunye/cc2"
description = "Tiny C Compiler"
categories = []
keywords = []

[dependencies]
